- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    username: myuser
  tasks:
  - name: Installation of Apache2 Web Server on RedHat/CentOS systems.
    yum:
      name: httpd
      state: latest
    notify:
    - startservice
  handlers:
  - name: startservice
    service:
      name: httpd
      state: restarted
- hosts: ubuntu
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    username: myuser
  tasks:
  - name: Installation of Apache2 Web Server on Ubuntu/Debian systems.
    yum:
      name: apache2
      state: latest
    notify:
    - startservice
  handlers:
  - name: startservice
    service:
      name: apache2
      state: restarted
